### ISSUE TITLE
"codigoRetorno"=>"7", "mensagemRetorno"=>"Vers\u00E3o desatualizada. Favor atualizar aplicativo."

### ISSUE THREAD

**Issue by bomrafinha** [aschiavon91/sinesp_client#1]
Olá, tudo bem, estou tentando usar o pacote mas está me retornando o erro em anexo. Talvez eu não esteja sabendo como usar, se puderes me dar uma luz lhe agradeço muito.

![image](https://user-images.githubusercontent.com/31997765/35761073-dc1127a6-086b-11e8-8434-c52a79418950.png)

**Comment by aschiavon91** [comment]
opa @bomrafinha, a sinesp tinha atualizado a versão da api.
Acabei de subir um fix, instale a versão 0.1.5 da gem que vai funcionar.

`gem install sinesp_client_v2 0.1.5`

**Comment by bomrafinha** [comment]
Desculpe ser chato, mas mudou o _require "sinesp_client_v2"_ ? Pq apesar de ter instalado a gema corretamente está dando o seguinte erro ao tentar carregar:

![image](https://user-images.githubusercontent.com/31997765/35810728-d07009d0-0a73-11e8-8988-07582d85a235.png)

**Comment by aschiavon91** [comment]
Sem problemas cara, tamo ai pra ajudar.
Então, desculpa, mas parece que tinha algum problema na hora de incluir os arquivos da gem.
Agora parece estar tudo certo.
```bash
gem install sinesp_client_v2 0.1.7
```

**Comment by bomrafinha** [comment]
Agora funcionou perfeitamente. Ainda estou meio "cru" em Ruby, mas se de alguma forma eu puder contribuir para o projeto, é só chamar, é uma ótima iniciativa e provavelmente usarei bastante essa gema.

![image](https://user-images.githubusercontent.com/31997765/35825444-fba69230-0a9c-11e8-871d-46c5330bd87c.png)

**Comment by bomrafinha** [comment]
Eu estou precisando uma gema que me retorne se o veiculo possuí alguma multa. Você teria alguma desse tipo? Não importa se for paga.
